### ISSUE TITLE
macos traffic lights not working on windows 11 

### ISSUE THREAD

**Issue by kb12000** [SlippingGittys-Discord-Themes/surCord#45]
after the latest discord update, macos traffic lights not working on windows 11

**Comment by SlippingGitty** [comment]
Thanks for the report, I will get to this when I have the time. I don't exactly have a Windows installation on me at the moment, as I'm primarily a macOS user. I'll spin a virtual machine.

This theme incorporates another theme called "macOS title bar", maintained by LuckFire. If you'd like to scream at them to fix it, be my guess. Otherwise, I'll be happy to fix it when I have the chance. 

Thanks again!

**Comment by kb12000** [comment]
thanks....i have reported the issue to them as well..

**Comment by kb12000** [comment]
https://dablulite.github.io/css-snippets/MacosTitlebar/import.css
 @SlippingGitty this one fixed the issue for me.

**Comment by SlippingGitty** [comment]
should take a minute for it to update, but otherwise-- let me know if it's fixed. i merged the fixes.

**Comment by kb12000** [comment]
yeah its absolutely fixed now.
